This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./OCOPEE.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file OCOPEE.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file OCOPEE.acr....done (6 lines written, 0 warnings).
Output written in OCOPEE.acr.
Transcript written in OCOPEE.alg.
